# Generated by Django 3.1.2 on 2020-10-17 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='direct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleFile', models.CharField(max_length=50, verbose_name='Имя файла')),
                ('samFile', models.FileField(upload_to='')),
                ('timeFile', models.DateTimeField(verbose_name='Время пупбликации')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
    ]
