# Generated by Django 3.1.2 on 2020-10-18 00:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direct',
            name='samFile',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='direct',
            name='timeFile',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
