# Generated by Django 3.1.2 on 2020-10-18 14:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201018_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direct',
            name='samFile',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='direct',
            name='titleFile',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Имя файла'),
        ),
    ]
